#!/bin/bash
port=$1
sudo apt-get -y install nodejs
sudo apt-get -y install npm
sudo apt-get -y install git-all
sudo apt-get -y install mysql-server
sudo apt-get -y install mysql-client
sudo systemctl start mysql
sudo mysql -u root -e "FLUSH PRIVILEGES;"
sudo mysql -u root -D mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'password';"
sudo systemctl restart mysql
sudo mysql -u root -e "CREATE DATABASE ensolversdb;"
sudo mysql -u root -ppassword -D ensolversdb -e "CREATE TABLE task_list(id INT NOT NULL AUTO_INCREMENT,folderID INT NOT NULL,taskname VARCHAR(45) NOT NULL,completed TINYINT(1),PRIMARY KEY(id));"
sudo mysql -u root -ppassword -D ensolversdb -e "CREATE TABLE folder_list(id INT NOT NULL AUTO_INCREMENT,folderName VARCHAR(45) NOT NULL,PRIMARY KEY(id));"
sudo mysql -u root -ppassword -D ensolversdb -e "CREATE TABLE users_list (id INT NOT NULL AUTO_INCREMENT,username VARCHAR(45) NOT NULL,password VARCHAR(45) NOT NULL,PRIMARY KEY(id));"
sudo mysql -u root -ppassword -D ensolversdb -e 'INSERT INTO users_list VALUE ("1",) "admin", "admin";'
mkdir ensolvers-interview-implementation
cd ensolvers-interview-implementation
git clone https://github.com/tomi2108/Ensolvers-interview-implementation.git
cd Ensolvers-interview-implementation
rm serverConfig.json
echo '{"serverConfig":{"port": "'$port'","url": "http://localhost"}}' > serverConfig.json
cd server
npm install express
npm install body-parser
npm install cors
npm install mysql
gnome-terminal -- npm start &
cd ..
cd client
cd src
rm serverConfig.json
echo '{"serverConfig":{"port": "'$port'","url": "http://localhost"}}' > serverConfig.json
cd ..
npm install react
npm install bootstrap
npm install react-bootstrap
npm install axios
npm install serve
serve -s build